app:
  port: 3000
  # 是否进入调试模式
  debug: false

bit:
  mode: testnet # 网络模式，可选：mainnet、testnet

log:
  level: info

# 数据库配置
database:
  # 默认数据库
  connection: mysql
  mysql:
    master:
      host: 43.133.76.72
      port: 3306
      database: ds_test
      username: ds_test
      password: 8c3JwskPtMEyhtcZ
      charset: utf8mb4
    # 连接池配置
    max_idle_connections: 100
    max_open_connections: 25
    max_life_seconds: 300

template_path: storage/template/test_nft.html

service_fee:
  amount: 80000
  receive_address: bc1pq93rmmn5v2kyj5mqvftu8pshm3tmccen8jhcsqrjwnhtjm7p0f8spuqa74

block_height_range:
  start: 1
  end: 5871600