app:
  port: 3000
  # 是否进入调试模式
  debug: true

bit:
  mode: testnet # 网络模式，可选：mainnet、testnet

# 数据库配置
database:
  # 默认数据库
  connection: mysql
  mysql:
    master:
      host: 127.0.0.1
      port: 3306
      database: ds
      username: root
      password: 123456
      charset: utf8mb4
    # 连接池配置
    max_idle_connections: 100
    max_open_connections: 25
    max_life_seconds: 300

template_path: storage/template/insc_cm_testnet.html

service_fee:
  amount: 1000
  receive_address: tb1pclrhuqrlwr2ykdd2muhnnxg2t8umepdndmar5wc4ua0z5wn86qssstj6kj